# Generated by Django 5.2.1 on 2026-05-19 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "مسؤول النظام"),
                            ("MANAGER", "مدير التشكيل"),
                            ("ORGANIZER", "منظم الاستمارة"),
                            ("REVIEWER", "مراجع"),
                            ("VIEWER", "مشاهد"),
                        ],
                        default="ORGANIZER",
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "full_name_ar",
                    models.CharField(
                        max_length=200, verbose_name="الاسم الكامل بالعربية"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="formations.formation",
                        verbose_name="التشكيل",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف مستخدم",
                "verbose_name_plural": "ملفات المستخدمين",
                "indexes": [
                    models.Index(fields=["role"], name="accounts_us_role_e16858_idx")
                ],
            },
        ),
    ]
