# Generated by Django 5.2.1 on 2026-05-20 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("formations", "0002_user_formation_one_to_one_and_formation_fk_on_goal_risk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="formation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_profile",
                to="formations.formation",
                verbose_name="formation",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="full_name_ar",
            field=models.CharField(max_length=200, verbose_name="full name in arabic"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "System Admin"),
                    ("MANAGER", "Formation Manager"),
                    ("ORGANIZER", "Form Organizer"),
                    ("REVIEWER", "Reviewer"),
                    ("VIEWER", "Viewer"),
                ],
                default="ORGANIZER",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
