# Generated by Django 5.2.1 on 2026-05-19 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LookupValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("KPI_TYPE", "نوع مؤشر الأداء"),
                            ("GOAL_TYPE", "نوع الهدف"),
                            ("PROBABILITY", "احتمالية المخاطر"),
                        ],
                        max_length=50,
                        verbose_name="الفئة",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="الرمز")),
                (
                    "label_ar",
                    models.CharField(max_length=200, verbose_name="التسمية بالعربية"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ترتيب العرض"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "قيمة قائمة",
                "verbose_name_plural": "قيم القوائم",
                "ordering": ["category", "sort_order", "label_ar"],
                "unique_together": {("category", "code")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "إنشاء"),
                            ("UPDATE", "تعديل"),
                            ("DELETE", "حذف"),
                            ("LOGIN", "تسجيل دخول"),
                            ("LOGOUT", "تسجيل خروج"),
                            ("EXPORT", "تصدير"),
                        ],
                        max_length=50,
                        verbose_name="الإجراء",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="النموذج"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="معرف الكائن"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="تمثيل الكائن"
                    ),
                ),
                (
                    "changes_json",
                    models.JSONField(blank=True, null=True, verbose_name="التغييرات"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الإجراء"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجلات التدقيق",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="core_auditl_model_n_3fb686_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_auditl_created_dc23ea_idx"
                    ),
                ],
            },
        ),
    ]
