# Generated by Django 5.2.1 on 2026-05-19 10:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_year",
                    models.PositiveSmallIntegerField(verbose_name="سنة الخطة"),
                ),
                (
                    "manager_name",
                    models.CharField(max_length=200, verbose_name="اسم مدير التشكيل"),
                ),
                (
                    "organizer_name",
                    models.CharField(max_length=200, verbose_name="اسم منظم الاستمارة"),
                ),
                (
                    "endorsement_text",
                    models.TextField(blank=True, null=True, verbose_name="نص المصادقة"),
                ),
                (
                    "endorsement_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ المصادقة"
                    ),
                ),
                (
                    "endorsement_ref_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="رقم الإشارة"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("SUBMITTED", "مقدمة"),
                            ("UNDER_REVIEW", "قيد المراجعة"),
                            ("APPROVED", "معتمدة"),
                            ("REJECTED", "مرفوضة"),
                            ("ARCHIVED", "مؤرشفة"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, null=True, verbose_name="سابعاً – التوصيات النهائية"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التقديم"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاعتماد"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأ بواسطة",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annual_plans",
                        to="formations.formation",
                        verbose_name="التشكيل",
                    ),
                ),
            ],
            options={
                "verbose_name": "خطة سنوية",
                "verbose_name_plural": "الخطط السنوية",
                "ordering": ["-plan_year", "formation__name_ar"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(verbose_name="الترتيب")),
                ("code", models.CharField(max_length=20, verbose_name="رمز الهدف")),
                ("title", models.TextField(verbose_name="الهدف الرئيسي")),
                (
                    "kpi_type",
                    models.CharField(
                        max_length=100, verbose_name="مؤشر الأداء الرئيسي (KPI)"
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(max_length=50, verbose_name="نوع الهدف"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="plans.annualplan",
                        verbose_name="الخطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "هدف",
                "verbose_name_plural": "الأهداف",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(verbose_name="الترتيب")),
                ("code", models.CharField(max_length=20, verbose_name="رمز النشاط")),
                ("title", models.TextField(verbose_name="المهمة / النشاط")),
                (
                    "required_resources",
                    models.TextField(
                        blank=True, null=True, verbose_name="الموارد المطلوبة"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                (
                    "planned_completion_pct",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نسبة الإنجاز المخطط (%)",
                    ),
                ),
                (
                    "actual_completion_pct",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نسبة الإنجاز المتحقق (%)",
                    ),
                ),
                (
                    "activity_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "لم يبدأ"),
                            ("IN_PROGRESS", "قيد الإنجاز"),
                            ("COMPLETED", "مكتمل"),
                            ("DELAYED", "متأخر"),
                            ("ROLLED_OVER", "تم ترحيله"),
                            ("STOPPED", "متوقف"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                        verbose_name="حالة النشاط",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "responsible_formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_activities",
                        to="formations.formation",
                        verbose_name="التشكيل المسؤول",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="plans.goal",
                        verbose_name="الهدف",
                    ),
                ),
            ],
            options={
                "verbose_name": "نشاط",
                "verbose_name_plural": "الأنشطة",
                "ordering": ["goal__sequence", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="PlanWorkflowLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("SUBMITTED", "مقدمة"),
                            ("UNDER_REVIEW", "قيد المراجعة"),
                            ("APPROVED", "معتمدة"),
                            ("REJECTED", "مرفوضة"),
                            ("ARCHIVED", "مؤرشفة"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="الحالة السابقة",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "مسودة"),
                            ("SUBMITTED", "مقدمة"),
                            ("UNDER_REVIEW", "قيد المراجعة"),
                            ("APPROVED", "معتمدة"),
                            ("REJECTED", "مرفوضة"),
                            ("ARCHIVED", "مؤرشفة"),
                        ],
                        max_length=20,
                        verbose_name="الحالة الجديدة",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="التعليق"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإجراء"
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نفّذ بواسطة",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_logs",
                        to="plans.annualplan",
                        verbose_name="الخطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل سير العمل",
                "verbose_name_plural": "سجلات سير العمل",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_description", models.TextField(verbose_name="الخطر المحتمل")),
                (
                    "probability",
                    models.CharField(
                        choices=[
                            ("LOW", "منخفض"),
                            ("MEDIUM", "متوسط"),
                            ("HIGH", "عالي"),
                        ],
                        max_length=10,
                        verbose_name="احتمالية الحدوث",
                    ),
                ),
                ("impact_description", models.TextField(verbose_name="التأثير")),
                (
                    "treatment_plan",
                    models.TextField(verbose_name="خطة المعالجة البديلة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="plans.annualplan",
                        verbose_name="الخطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مخاطرة",
                "verbose_name_plural": "المخاطر",
                "ordering": ["probability", "id"],
            },
        ),
        migrations.CreateModel(
            name="SwotAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strengths",
                    models.TextField(blank=True, null=True, verbose_name="نقاط القوة"),
                ),
                (
                    "weaknesses",
                    models.TextField(blank=True, null=True, verbose_name="نقاط الضعف"),
                ),
                (
                    "opportunities",
                    models.TextField(blank=True, null=True, verbose_name="الفرص"),
                ),
                (
                    "threats",
                    models.TextField(blank=True, null=True, verbose_name="التهديدات"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swot",
                        to="plans.annualplan",
                        verbose_name="الخطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحليل SWOT",
                "verbose_name_plural": "تحليلات SWOT",
            },
        ),
        migrations.AddIndex(
            model_name="annualplan",
            index=models.Index(fields=["status"], name="plans_annua_status_26fab6_idx"),
        ),
        migrations.AddIndex(
            model_name="annualplan",
            index=models.Index(
                fields=["plan_year"], name="plans_annua_plan_ye_cea4ea_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="annualplan",
            unique_together={("formation", "plan_year")},
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["plan"], name="plans_goal_plan_id_2079a5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="goal",
            unique_together={("plan", "sequence")},
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["activity_status"], name="plans_activ_activit_bea455_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["start_date", "end_date"], name="plans_activ_start_d_744ff7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together={("goal", "sequence")},
        ),
        migrations.AddIndex(
            model_name="planworkflowlog",
            index=models.Index(fields=["plan"], name="plans_planw_plan_id_f822c9_idx"),
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(fields=["plan"], name="plans_risk_plan_id_f52c13_idx"),
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(
                fields=["probability"], name="plans_risk_probabi_e981c4_idx"
            ),
        ),
    ]
