# Generated by Django 5.2.1 on 2026-05-20 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_goal_and_risk_formation(apps, schema_editor):
    """Copy formation from AnnualPlan into Goal.formation and Risk.formation."""
    Goal = apps.get_model('plans', 'Goal')
    Risk = apps.get_model('plans', 'Risk')

    goals_to_update = []
    for goal in Goal.objects.select_related('plan').filter(formation__isnull=True):
        goal.formation = goal.plan.formation
        goals_to_update.append(goal)
    Goal.objects.bulk_update(goals_to_update, ['formation'])

    risks_to_update = []
    for risk in Risk.objects.select_related('plan').filter(formation__isnull=True):
        risk.formation = risk.plan.formation
        risks_to_update.append(risk)
    Risk.objects.bulk_update(risks_to_update, ['formation'])


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0002_user_formation_one_to_one_and_formation_fk_on_goal_risk"),
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annualplan",
            options={
                "ordering": ["-plan_year", "formation__name_ar"],
                "verbose_name": "annual plan",
                "verbose_name_plural": "annual plans",
            },
        ),
        migrations.AddField(
            model_name="goal",
            name="formation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goals",
                to="formations.formation",
                verbose_name="التشكيل",
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="formation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="risks",
                to="formations.formation",
                verbose_name="التشكيل",
            ),
        ),
        migrations.RunPython(
            backfill_goal_and_risk_formation,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="approved at"
            ),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="endorsement_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="endorsement date"
            ),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="endorsement_ref_no",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="reference number"
            ),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="endorsement_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="endorsement text"
            ),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="formation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annual_plans",
                to="formations.formation",
                verbose_name="formation",
            ),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="manager_name",
            field=models.CharField(max_length=200, verbose_name="manager name"),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="organizer_name",
            field=models.CharField(max_length=200, verbose_name="organizer name"),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="plan_year",
            field=models.PositiveSmallIntegerField(verbose_name="plan year"),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="recommendations",
            field=models.TextField(
                blank=True, null=True, verbose_name="recommendations"
            ),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="submitted at"
            ),
        ),
        migrations.AlterField(
            model_name="annualplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
