# Generated by Django 5.2.1 on 2026-05-19 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="الرمز"),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="الاسم بالعربية"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("COMPANY", "شركة"),
                            ("BOARD", "هيأة"),
                            ("DIVISION", "قسم"),
                            ("SECTION", "شعبة"),
                            ("UNIT", "وحدة"),
                        ],
                        max_length=20,
                        verbose_name="المستوى",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="formations.formation",
                        verbose_name="التشكيل الأعلى",
                    ),
                ),
            ],
            options={
                "verbose_name": "تشكيل",
                "verbose_name_plural": "التشكيلات",
                "ordering": ["level", "name_ar"],
                "indexes": [
                    models.Index(fields=["level"], name="formations__level_033282_idx")
                ],
            },
        ),
    ]
