# Generated by Django 5.2.1 on 2026-05-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formation",
            options={
                "ordering": ["level", "name_ar"],
                "verbose_name": "formation",
                "verbose_name_plural": "formations plural",
            },
        ),
        migrations.AlterField(
            model_name="formation",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="formation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="formation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AlterField(
            model_name="formation",
            name="level",
            field=models.CharField(
                choices=[
                    ("COMPANY", "Company"),
                    ("BOARD", "Board"),
                    ("DIVISION", "Division"),
                    ("SECTION", "Section"),
                    ("UNIT", "Unit"),
                ],
                max_length=20,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="formation",
            name="name_ar",
            field=models.CharField(max_length=200, verbose_name="name in arabic"),
        ),
        migrations.AlterField(
            model_name="formation",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="formations.formation",
                verbose_name="parent formation",
            ),
        ),
        migrations.AlterField(
            model_name="formation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
