# Generated by Django 5.2.1 on 2026-05-31 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0002_user_formation_one_to_one_and_formation_fk_on_goal_risk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Parent Formation",
                "verbose_name_plural": "Parent Formations",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="formation",
            name="parent_formation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="formations",
                to="formations.parentformation",
                verbose_name="Parent Formation Category",
            ),
        ),
    ]
