# Generated by Django 5.2.1 on 2026-05-31 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0003_parentformation_formation_parent_formation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formation",
            name="parent",
        ),
    ]
