# Generated by Django 5.2.1 on 2026-05-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0004_remove_formation_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formation",
            name="code",
        ),
        migrations.AlterField(
            model_name="formation",
            name="level",
            field=models.CharField(
                choices=[
                    ("COMPANY", "Company"),
                    ("BOARD", "Division"),
                    ("DIVISION", "Department"),
                    ("SECTION", "Section"),
                    ("UNIT", "Unit"),
                ],
                max_length=20,
                verbose_name="Level",
            ),
        ),
    ]
